mysql:
  # The host can be one of three options:
  # 1. localhost
  # 2. IP address of a remote server
  # 3. Name of a MySQL Docker service
  host: "mysql"
  user: "root"
  password: ""
  database: "bek"
